apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager/apps-cert-manager.yaml
  - cert-manager/apps-cluster-issuer.yaml
  - cloudflared/cloudflare-api-token-sealed-secret.yaml
  - cloudflared/cloudflare-tunnel-token-sealed-secret.yaml
  - cloudflared/cloudflared-tunnel.yaml
  - ingress/website-ingress.yaml
  - website/website-deployment.yaml
  - website/website-service.yaml
  - sealed-secrets/apps-sealed-secrets.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: k3s-project
      app.kubernetes.io/managed-by: argocd
