apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuer.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: k3s-project
      app.kubernetes.io/managed-by: argocd
