apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metrics/apps-prometheus-config.yaml
  - metrics/apps-kube-prometheus-stack.yaml
  - metrics/apps-loki.yaml
  - metrics/apps-alloy.yaml
