apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-config
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: monitoring
  annotations:
    description: "DÃ©finition des configurations pour Prometheus (ServiceMonitor, Rule, AlertManager, etc.)"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    # - repoURL: 'https://github.com/mathisDlmr/k3s-project.git'
    #   targetRevision: main
    #   path: monitoring/metrics/alert-manager/
    - repoURL: "https://github.com/mathisDlmr/k3s-project.git"
      targetRevision: main
      path: monitoring/metrics/rules/
    - repoURL: "https://github.com/mathisDlmr/k3s-project.git"
      targetRevision: main
      path: monitoring/metrics/service-monitors/
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
