apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k3s-servicemonitor.yaml
  - k3s-kube-proxy-servicemonitor.yaml
  - k3s-coredns-servicemonitor.yaml
  - node-exporter-servicemonitor.yaml
  - skiut-backend-servicemonitor.yaml
  - skiut-mysql-servicemonitor.yaml
