apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: infra
data:
  config.yaml: |
    tunnel: mdlmr-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json

    ingress:
      - hostname: mdlmr.fr
        service: https://traefik.traefik.svc.cluster.local
      - hostname: *.mdlmr.fr
        service: https://traefik.traefik.svc.cluster.local      
      - service: http_status:404
