apiVersion: v1
kind: ConfigMap
metadata:
  name: skiut-backend-configmap
data:
  OAUTH_REDIRECT_URI: https://skiut.mdlmr.fr/skiutc/auth/callback
  OAUTH_BACKOFFICE_REDIRECT_URI: https://skiut.mdlmr.fr/skiutc/auth/back-office/callback
