apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skiut-ingress
  namespace: skiut
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: skiut.mdlmr.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skiut-backend
                port:
                  number: 80
  tls:
    - hosts:
        - skiut.mdlmr.fr
