apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiut-backend
  namespace: skiut
spec:
  replicas: 3
  selector:
    matchLabels:
      app: skiut-backend
  template:
    metadata:
      labels:
        app: skiut-backend
    spec:
      containers:
        - name: skiut-backend
          image: ghcr.io/ski-utc/server-skiut-2026:2d5fd718235117c941a145ed77742f03fc2ed99e
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: laravel-storage
              mountPath: /var/www/html/storage
          env:
            - name: LOG_CHANNEL
              value: stderr
            - name: OTEL_SDK_DISABLED
              value: "false"
            - name: APP_ENV
              value: production
            - name: APP_URL
              value: https://skiut.mdlmr.fr
            - name: USER_ID
              value: "24"
            - name: APP_NO_LOGIN
              value: "false"
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: skiut-database-configmap
                  key: MYSQL_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: skiut-database-configmap
                  key: MYSQL_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: skiut-database-configmap
                  key: MYSQL_DB
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: skiut-database-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skiut-database-secret
                  key: MYSQL_PASSWORD
            - name: SIMDE_KEY
              valueFrom:
                secretKeyRef:
                  name: skiut-backend-secret
                  key: SIMDE_KEY
            - name: OAUTH_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: skiut-backend-configmap
                  key: OAUTH_REDIRECT_URI
            - name: OAUTH_BACKOFFICE_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: skiut-backend-configmap
                  key: OAUTH_BACKOFFICE_REDIRECT_URI
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: skiut-backend-secret
                  key: OAUTH_CLIENT_ID
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: skiut-backend-secret
                  key: OAUTH_CLIENT_SECRET
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: skiut-backend-secret
                  key: WEATHER_API_KEY
      volumes:
        - name: laravel-storage
          persistentVolumeClaim:
            claimName: skiut-backend-storage
